dist: trusty

language: python

python:
 - 2.7
 - 3.6
 - 3.5
 - 3.4
 - 3.3

# Use container-based infrastructure
sudo: false

install:
 - pip install -U pip
 - pip install pyflakes
 - pip install tensorflow

 # Make a smaller input file. Output won't look great, but runs much quicker.
 - mkdir data/teenytinyshakespeare
 - head -100 data/tinyshakespeare/input.txt > data/teenytinyshakespeare/input.txt

script:
 - pyflakes .
 - python train.py --data_dir data/teenytinyshakespeare
 - python train.py --data_dir data/teenytinyshakespeare --init_from save
 - python sample.py

after_script:
 - pip install pep8
 - pep8 --statistics --count .
